"""
Django settings for cmsAuth project.

Generated by 'django-admin startproject' using Django 1.10.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""
# cmsAuth - http://github.com/slosimon/cmsAuth/
# Copyright © 2016 Simon Weiss <weiss.simon.1995@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.from django.shortcuts

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname((__file__)))
URL = 'http://your-domain/cmsAuth/' #Change this into your registration address
CMS_URL = 'http://your-domain/' #change this into your CMS login address
CONTEST_ID = '3' #change into your CMS contest ID that is on the go

ACTIVATE = 'aktiviraj' #translate into your language (used as url so no spaces or special caracters and do the sae to NEW_PASSWORD (INCLUDED)
NEW_LINK = 'nova-povezava' #
THANKS = 'hvala' #
RECIEVED = 'sprejeto' #
SUCCESS = 'uspeh' #
LOST_PASSWORD = 'pozabljeno-geslo' #
NEW_PASSWORD = 'novo-geslo' #
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'v$ltz3+jj9o@m_d&hh6367c6#p=s)*(r&9dbw5k#p+z@f$2r^8' #generate new

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['your domain'] #change this. if you don't have any, change DEBUG = True. But it might lead into security problems


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'users',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
#    'aut',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cmsAuth.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
	     BASE_DIR+"/templates",
	],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cmsAuth.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'cmsdb',
	'USER': 'cmsuser',
	'PASSWORD': '', #enter your cmsdb password
	'HOST': 'localhost', #change if DB hosted on other server
	'PORT': '',
    }
}

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)
# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'sl' #change into your language code

TIME_ZONE = 'CET' #change into your timezone

USE_I18N = True

USE_L10N = True

USE_TZ = True

prefix_default_language=False
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/
TEMPLATE_DIRS = (
    os.path.dirname(__file__) + '/templates',
)
EMAIL_USE_TLS = True
EMAIL_HOST = '' #enter url to smtp
EMAIL_HOST_USER = '' #enter your email username
EMAIL_HOST_PASSWORD = '' #enter your email account password
EMAIL_PORT = #enter EMAIL port 
STATIC_URL = CMS_URL+'static/' #Or whatoever
STATIC_ROOT = "~/cms/cms/server/static/" #Navigate to cms
